### ISSUE TITLE
Jekyll won't link to other pages on github

### ISSUE THREAD

**Issue by stephyspiccoli** [stephyspiccoli/portfolio#2]
Hi Thomas,

So I started adding jekyll and so far it worked but as soon as I linked to the other pages github just read as file not found.

The problem is that I added jekyll to the link I submitted the interactive wireframes for you so now I don't know how to fix it so you don't see it when marking.

@thomasjbradley

**Comment by thomasjbradley** [comment]
Have you tried removing the `.html` part from the links in your HTML?

Here's an example—change this link:

```html
<a class="" href="{{site.baseurl}}/isometric.html">
```

To this…


```html
<a class="" href="{{site.baseurl}}/isometric/">
```
