### ISSUE TITLE
Toggle nav won't work

### ISSUE THREAD

**Issue by stephyspiccoli** [stephyspiccoli/portfolio#3]
@thomasjbradley

Hi Thomas,

I can't seem to get my toggle to work properly. I still get my checkbox and my nav items appear so low on the banner.

Thank you

**Comment by thomasjbradley** [comment]
*Re: hiding the checkbox—*

Add the class `.hide-custom-input` and it should go away.

---

*Re: nav position—*

I see that it’s set to `position: absolute`—which is okay. But the top is set to `100%` which means it’ll move down 100% the height of its parent element.
