### ISSUE TITLE
Java scrip doens't work

### ISSUE THREAD

**Issue by stephyspiccoli** [stephyspiccoli/portfolio#6]
Hi Thomas,

I added Java Script for smooth scrolling but it is not working on my github link.

I am not sure if I forgot to link something

@thomasjbradley

**Comment by thomasjbradley** [comment]
Try switching to `{{site.baseurl}}` instead of `..` in the JS `src` attribute:
https://github.com/stephyspiccoli/portfolio/blob/gh-pages/_layouts/default.html#L32
