### ISSUE TITLE
Problem with toggle nav

### ISSUE THREAD

**Issue by stephyspiccoli** [stephyspiccoli/portfolio#7]
Hi thomas,

@thomasjbradley

I have two questions for you. I have a toggle nav that when I open it takes up the whole screen but the issue I am having is I would like my nav to be block when is open but it remains inline-block and I have tried targeting several elements and I am not able to change it.

**Comment by thomasjbradley** [comment]
This line of CSS is the culprit:
https://github.com/stephyspiccoli/portfolio/blob/gh-pages/css/main.css#L65-L67

I think it should be moved into the media query where the toggle navigation disappears.
